name: Create Release on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  create-release:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Get latest tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - name: Delete latest tag if PR is not merged
        if: github.event.pull_request.merged == false
        run: |
          git tag -d ${{ steps.get-latest-tag.outputs.tag }}
          git push origin :refs/tags/${{ steps.get-latest-tag.outputs.tag }}

      - name: Get tag message
        if: github.event.pull_request.merged == true
        run: |
          TAG_MESSAGE=$(git tag -l --format='%(contents)' ${GITHUB_REF#refs/tags/})
          echo "TAG_MESSAGE=$TAG_MESSAGE" >> $GITHUB_ENV

      - name: Create release
        if: github.event.pull_request.merged == true
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.get-latest-tag.outputs.tag }}
          release_name: ${{ steps.get-latest-tag.outputs.tag }}
          body: ${{ env.TAG_MESSAGE }}
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
